apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0a891336-1214-4a19-953e-1744629c87b1"
    keyvaultName: devops-kv-demo
    tenantId: 2eff0ba1-563c-462f-802b-2d1786954ca6

    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""